
enum bootstrapReq
{
	BSD_REQ_NONE,
    BSD_REQ_CHECK_SERVER,
    BSD_REQ_STOP_SERVER,
	BSD_REQ_GET_SBTOKEN,
	BSD_REQ_ENABLE_JIT,
	BSD_REQ_ENABLE_JIT2,
	BSD_REQ_SSH_CHECK,
    BSD_REQ_SSH_START,
    BSD_REQ_SSH_STOP,
	BSD_REQ_MAX_REQ
};
