#!/bin/sh

ls /Applications/  | while read app; do
    echo "--$app--";
    unlink "/Applications/$app/.preload"
    unlink "/Applications/$app/.prelib"
    link /basebin/preload "/Applications/$app/.preload"
    link /basebin/preload.dylib "/Applications/$app/.prelib"
done

ls -d /var/containers/Bundle/Application/*/*.app/.jbroot | while read file; do
    bundle=$(dirname "$file")
    echo "--$bundle--"

    unlink "$bundle"/.jbroot
    ln -s /  "$bundle"/.jbroot

    unlink "$bundle"/.preload
    unlink "$bundle"/.prelib
    link /basebin/preload "$bundle"/.preload
    link /basebin/preload.dylib "$bundle"/.prelib
done
